### ISSUE TITLE
Problem with MathJS in "grant" section

### ISSUE THREAD

**Issue by easye** [acid-info/Codex.storage#4]
<https://codex.storage/grant> fails to render due to MathJS problem.

![image](https://user-images.githubusercontent.com/864261/176846457-91223c4a-8b8e-41bc-9f21-2a3aa7ad4c56.png)

Replicated on macOS Chrome/Firefox Eternal

**Comment by amirhouieh** [comment]
You need to add `_includes: [math]` to the front matter of the markdown file like following
```
_includes: [math]
```

here are a couple of examples 
https://github.com/vacp2p/vac.dev/blob/92668b43b333a78a535770a65a44b18735e77d07/research/2022-05-09-ambient-peer-discovery.md

https://github.com/vacp2p/vac.dev/blob/92668b43b333a78a535770a65a44b18735e77d07/research/2022-05-17-noise.md

🤞
