### ISSUE TITLE
Blog posts from Ghost API not showing up

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/codex.storage#6]
Codex shows a list of recent blog posts they have published using their Ghost instance. The client that fetches these posts from Ghost API requires API key which is stored as env var called `GHOST_API_KEY`
https://github.com/acid-info/codex.storage/blob/b5b8eef840b1315a5f8b171ad15e8b819d0f59af/docusaurus.config.js#L12

**Comment by jakubgs** [comment]
I created one: `dc7884e3d2c10dde2269926b20`

![image](https://user-images.githubusercontent.com/2212681/227210172-fed93cb9-8de5-468d-a863-b1e599631706.png)

They key is not secret, it will be available for inspection in dev console when viewing requests made.

**Comment by serhanwbahar** [comment]
Done:
https://github.com/acid-info/codex.storage/pull/8

@amirhouieh if all is well I'll close the issue.

**Comment by amirhouieh** [comment]
@serhanwbahar API key is in good order. But it seems that we have a problem with API calls in the browser. We get the error code "ERR_NETWORK". I suspect this to be related to #7

**Comment by serhanwbahar** [comment]
@amirhouieh now it should be working. Could you please check it?
* https://github.com/status-im/infra-misc/pull/128

**Comment by amirhouieh** [comment]
@serhanwbahar this is resolved, thanks!
