### ISSUE TITLE
External resources are blocked by Content Security Policy 🤔 ?

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/codex.storage#7]
After the new deployment, some of the external resources get blocked apparently due to CSP. 

@serhanwbahar could you please look into this?
![image](https://user-images.githubusercontent.com/7159454/227205931-c7e4f13d-069d-4284-9675-e3fc2ec55b8e.png)

**Comment by serhanwbahar** [comment]
Fixed.

* https://github.com/status-im/infra-misc/pull/128
